In [2]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [6]:
# using empty
a = torch.empty(2,3)

In [8]:
# check type
type(a)

torch.Tensor

In [10]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# using rand
torch.rand(2,3)

tensor([[0.8357, 0.5804, 0.9960],
        [0.9672, 0.5435, 0.2097]])

In [24]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [25]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [28]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [30]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
x.shape

torch.Size([2, 3])

In [40]:
torch.empty_like(x)

tensor([[              0,       171675984,       153688208],
        [133859306264912,               1,               6]])

In [41]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [48]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

## Tensor Data Types

In [49]:
# find data type
x.dtype

torch.int64

In [51]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [52]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [54]:
x.to(dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

### 1. Scalar operation

In [57]:
x = torch.rand(2,2)
x

tensor([[0.3182, 0.5261],
        [0.0447, 0.5123]])

In [72]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.1013, 0.2768],
        [0.0020, 0.2625]])

### 2. Element wise operation

In [73]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])
tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])


In [76]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2839, 0.0458, 0.4450],
        [0.3591, 0.4563, 0.3389]])

In [77]:
c = torch.tensor([1, -2, 3, -4])

In [78]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [79]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [80]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [81]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [82]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [84]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [86]:
# clamp
torch.clamp(d, min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [104]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 0., 8.],
        [4., 7., 2.]])

In [105]:
# sum
torch.sum(e)

tensor(25.)

In [106]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 8.,  7., 10.])

In [107]:
# sum along rows
torch.sum(e, dim=1)

tensor([12., 13.])

In [108]:
# mean
torch.mean(e)

tensor(4.1667)

In [109]:
# mean along col
torch.mean(e, dim=0)

tensor([4.0000, 3.5000, 5.0000])

In [110]:
# mean along rows
torch.mean(e, dim=1)

tensor([4.0000, 4.3333])

In [111]:
# median
torch.median(e)

tensor(4.)

In [119]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [120]:
# product
torch.prod(e)

tensor(0.)

In [121]:
# standard deviation
torch.std(e)

tensor(2.9944)

In [122]:
# variance
torch.var(e)

tensor(8.9667)

In [123]:
# argmax
torch.argmax(e)

tensor(2)

In [124]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [130]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 0, 4],
        [2, 7, 1]])
tensor([[1, 5],
        [4, 4],
        [1, 1]])


In [131]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 9, 29],
        [31, 39]])

In [132]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [133]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 2],
        [0, 7],
        [4, 1]])

In [134]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 4., 7.],
        [2., 5., 6.],
        [1., 4., 5.]])

In [135]:
# determinant
torch.det(h)

tensor(7.)

In [136]:
# inverse
torch.inverse(h)

tensor([[ 0.1429,  1.1429, -1.5714],
        [-0.5714,  0.4286,  0.2857],
        [ 0.4286, -0.5714,  0.2857]])

### 5. Comparison operations

In [137]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 9, 2],
        [3, 1, 0]])
tensor([[2, 1, 2],
        [7, 9, 2]])


In [140]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >=j
# less than equal to
i <=j

tensor([[False, False,  True],
        [ True,  True,  True]])

### 6. Special functions

In [142]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 7., 9.],
        [2., 7., 0.]])

In [143]:
# log
torch.log(k)

tensor([[  -inf, 1.9459, 2.1972],
        [0.6931, 1.9459,   -inf]])

In [144]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 1.0966e+03, 8.1031e+03],
        [7.3891e+00, 1.0966e+03, 1.0000e+00]])

In [145]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.6458, 3.0000],
        [1.4142, 2.6458, 0.0000]])

In [146]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9991, 0.9999],
        [0.8808, 0.9991, 0.5000]])

In [147]:
# softmax
torch.softmax(k, dim=0)

tensor([[1.1920e-01, 5.0000e-01, 9.9988e-01],
        [8.8080e-01, 5.0000e-01, 1.2339e-04]])

In [148]:
# relu
torch.relu(k)

tensor([[0., 7., 9.],
        [2., 7., 0.]])

## Inplace Operations

In [160]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])
tensor([[0.5569, 0.9952, 0.0015],
        [0.0813, 0.4907, 0.2130]])


In [161]:
m.add_(n)

tensor([[1.5384, 1.1084, 0.4798],
        [0.5249, 0.8755, 0.6651]])

In [162]:
m

tensor([[1.5384, 1.1084, 0.4798],
        [0.5249, 0.8755, 0.6651]])

In [163]:
n

tensor([[0.5569, 0.9952, 0.0015],
        [0.0813, 0.4907, 0.2130]])

In [164]:
torch.relu(m)

tensor([[1.5384, 1.1084, 0.4798],
        [0.5249, 0.8755, 0.6651]])

In [165]:
m.relu_()

tensor([[1.5384, 1.1084, 0.4798],
        [0.5249, 0.8755, 0.6651]])

## Copying a Tensor

In [166]:
a = torch.rand(2,3)
a

tensor([[0.4603, 0.1386, 0.0277],
        [0.5662, 0.3503, 0.6555]])

In [167]:
b = a

In [168]:
b

tensor([[0.4603, 0.1386, 0.0277],
        [0.5662, 0.3503, 0.6555]])

In [172]:
a[0][0]= 3234

In [173]:
a

tensor([[3.2340e+03, 1.3862e-01, 2.7686e-02],
        [5.6623e-01, 3.5030e-01, 6.5549e-01]])

In [174]:
b

tensor([[3.2340e+03, 1.3862e-01, 2.7686e-02],
        [5.6623e-01, 3.5030e-01, 6.5549e-01]])

In [175]:
id(a)

133859254145408

In [176]:
id(b)

133859254145408

In [177]:
b = a.clone()

In [178]:
a[0][0]= 0

In [179]:
a

tensor([[0.0000, 0.1386, 0.0277],
        [0.5662, 0.3503, 0.6555]])

In [ ]:
b

## Tensor Operation in GPU

In [9]:
torch.cuda.is_available()

True

In [10]:
device = torch.device('cuda')

In [11]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3123, 0.0845, 0.2945],
        [0.9552, 0.2726, 0.8134]], device='cuda:0')

In [12]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.6366, 0.6834, 0.4639],
        [0.4656, 0.9428, 0.0197]])

In [13]:
b=a.to(device)
b

tensor([[0.6366, 0.6834, 0.4639],
        [0.4656, 0.9428, 0.0197]], device='cuda:0')

In [14]:
b+5

tensor([[5.6366, 5.6834, 5.4639],
        [5.4656, 5.9428, 5.0197]], device='cuda:0')

## Reshaping Tensors

In [16]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [20]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
b = torch.rand(2,3,4)
b

tensor([[[0.1640, 0.6012, 0.0769, 0.3761],
         [0.1656, 0.5987, 0.1552, 0.2244],
         [0.9375, 0.2727, 0.3969, 0.8817]],

        [[0.4682, 0.0976, 0.5396, 0.6390],
         [0.4289, 0.0946, 0.0288, 0.5940],
         [0.3911, 0.1860, 0.6483, 0.1761]]])

In [35]:
# permute
b.permute(2,0,1)

tensor([[[0.1640, 0.1656, 0.9375],
         [0.4682, 0.4289, 0.3911]],

        [[0.6012, 0.5987, 0.2727],
         [0.0976, 0.0946, 0.1860]],

        [[0.0769, 0.1552, 0.3969],
         [0.5396, 0.0288, 0.6483]],

        [[0.3761, 0.2244, 0.8817],
         [0.6390, 0.5940, 0.1761]]])

In [36]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [37]:
# unsqueeze


In [41]:
c =torch.rand(226,226,3)
c.unsqueeze(dim=0)

tensor([[[[0.5862, 0.7625, 0.1167],
          [0.3556, 0.6162, 0.9210],
          [0.3679, 0.6406, 0.2524],
          ...,
          [0.3750, 0.0260, 0.2733],
          [0.2753, 0.4514, 0.1798],
          [0.7260, 0.7185, 0.6771]],

         [[0.6152, 0.2178, 0.1584],
          [0.5251, 0.1615, 0.4173],
          [0.7165, 0.2242, 0.1400],
          ...,
          [0.5091, 0.7837, 0.0703],
          [0.9598, 0.4051, 0.8759],
          [0.4764, 0.2986, 0.1788]],

         [[0.9880, 0.1652, 0.0745],
          [0.3068, 0.1349, 0.1529],
          [0.3719, 0.9215, 0.8627],
          ...,
          [0.3671, 0.8163, 0.6055],
          [0.7083, 0.9681, 0.7074],
          [0.7397, 0.8475, 0.7475]],

         ...,

         [[0.3364, 0.2724, 0.4542],
          [0.6563, 0.2224, 0.7471],
          [0.2182, 0.3559, 0.0555],
          ...,
          [0.8429, 0.5774, 0.9965],
          [0.8364, 0.1632, 0.6423],
          [0.4866, 0.6235, 0.6364]],

         [[0.7603, 0.5458, 0.7297],
          [0.4340

In [42]:
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [45]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0)

tensor([0.8092, 0.2947, 0.2983, 0.0283, 0.6771, 0.9524, 0.6675, 0.2643, 0.9189,
        0.1142, 0.9651, 0.0616, 0.1466, 0.1445, 0.9203, 0.1023, 0.7430, 0.2879,
        0.7711, 0.5089])

In [46]:
d.squeeze(0).shape

torch.Size([20])

## NumPy and PyTorch

In [47]:
import numpy as np

In [50]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [52]:
b =a.numpy()
b

array([1, 2, 3])

In [53]:
type(b)

numpy.ndarray

In [55]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [58]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])

In [59]:
type(d)

torch.Tensor